on: [push]

jobs:
  test_ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run fmt
        run: |
          deno fmt
      #- name: Run lint
      #  run: |
      #    deno lint
      - name: commit and push
        run: |
          git config --global user.email "workflow@example.com"
          git config --global user.name "workflow user"
          git add .
          git commit -m 'deno fmt' && git push ${REPO} HEAD:${{github.event.pull_request.head.ref}} || true
          git push

